### ISSUE TITLE
Clicking the edit button doesn't do anything.

### ISSUE THREAD

**Issue by lizardpeter** [stefanak-michal/cyphergui#45]
**Describe the bug**
Clicking the edit button doesn't do anything. No tab is opened for editing. Page flashes once but there is nowhere to edit.

**To Reproduce**
1. Connect to Memgraph database.
2. Click on a node to edit.
3. No way to edit.

**Expected behavior**
There should be a way to edit nodes.

**Screenshots**
None.

**Device (please complete the following information):**
 - OS: MacOS Ventura 13.6.4
 - Browser: Chrome 122.0.6261.69
 - Version: 0.2.3

**Additional context**
None.

**Comment by stefanak-michal** [comment]
Memgraph v2.15.0 in docker

**Comment by stefanak-michal** [comment]
Hi. Thanks for reporting this issue. Problem was with change related to neo4j javascript driver. Neo4j introduces elementId aside of id for nodes and relationships. And driver returns elementId on nodes and rels even when the database doesn't support it, it just fill it with id. So I improved check upon connection to verify if database is using elementId. You can enjoy new release with even new features.

https://github.com/stefanak-michal/cyphergui/releases/tag/v0.3.0
